version: '3'

services:
  maildev:
    image: maildev/maildev
    ports:
      - '1025:1025'
      - '1080:1080'
    environment:
      MAILDEV_INCOMING_USER: mailer
      MAILDEV_INCOMING_PASS: password
